# Generated by Django 2.2 on 2019-05-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Twice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='홍길동', max_length=20)),
                ('age', models.IntegerField()),
                ('birth', models.DateTimeField(verbose_name='date published')),
                ('nationality', models.CharField(choices=[('KR', '한국'), ('JP', '일본'), ('TW', '대만')], max_length=200)),
                ('position', models.TextField(max_length=20)),
            ],
        ),
    ]
